### ISSUE TITLE
As a user I would like to see how much time I have left to answer the question

### ISSUE THREAD

**Issue by dkuzma1** [sopra-fs23-group-39/sopra-server#80]
- [x] sopra-fs23-group-39/sopra-client#60
- [x] #82

**Comment by NieMark** [comment]
Goes hand in hand with https://github.com/sopra-fs23-group-39/sopra-client/issues/60 :

https://github.com/sopra-fs23-group-39/sopra-client/commit/39d8f0cbb3a6ecae8fb1aae51f36a13a58d04ad7
